# SPDX-License-Identifier: Apache-2.0

name: Test runs-on

on:
  workflow_dispatch:

jobs:
  this-uses-runs-on:
    runs-on: runs-on=${{ github.run_id }}/runner=2cpu-linux-x64
    steps:
      - name: "Harden Runner"
        # v2.10.1
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0
        with:
          egress-policy: audit

      - name: Checkout instructlab/training
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: ECHO
        run: echo "Hello world"
